module = "icon"

[glyphs]
edit = "fontawesome-pencil"
save = "entypo-floppy"
trash = "typicons-trash"
folder = "fontawesome-folder-open"
iconfile = "fontawesome-file-image"
open = "fontawesome-doc-text-inv"
text_cursor = "fontawesome-i-cursor"
palette = "entypo-palette"
settings = "fontawesome-cog-alt"
search = "fontawesome-search"
